homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 203
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

zone:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 500
  icon: mdi:worker

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_pwd
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: rams-ha.duckdns.org:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router
    - plex_mediaserver

binary_sensor:
  - platform: workday
    country: US

media_player:
  - platform: cast
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
  # - platform: firetv
  - platform: samsungtv
    host: 192.168.1.8
    name: Samsung TV
    mac: 78:AB:BB:E9:8D:AE

notify:
  - platform: ios
  - platform: pushbullet
    name: pushbullet
    api_key: o.IGPSlL4ImRGmc5YTGcgfG9SofvEjWyD1

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

device_tracker:
 - platform: nmap_tracker
   hosts: 192.168.1.1-255
   track_new_devices: no
   consider_home: 600
   interval_seconds: 60
   home_interval: 60
   scan_options: " --privileged -sP "
   # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap

camera:
  - platform: generic
    still_image_url: http://cdn.abclocal.go.com/three/wpvi/weather/16_9/hd/wpvi_f_1_1280.jpg
    scan_interval: 600
    name: Radar
  - platform: generic
    still_image_url: http://cdn.abclocal.go.com/three/wpvi/weather/midatlanticsatrad10_1280.jpg
    scan_interval: 600
    name: Radar Midatlantic
  - platform: generic
    still_image_url: http://www.ssd.noaa.gov/goes/east/eaus/avn.jpg
    scan_interval: 600
    name: Radar Noaa

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
input_boolean: !include input_boolean.yaml

logger: !include logger.yaml
recorder: !include recorder.yaml

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - media_player
  exclude:
    entities:
     - sensor.time__date
     - sensor.new_delhi
     - sensor.time_utc
     - sun.sun

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time__date
      - sensor.new_delhi
      - sensor.time_utc